version: '3.9'

services:
  web:
    build: .
    command: bash -c "python src/main.py"
    container_name: dm-users-service
    volumes:
      - .:/dm-users-service
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy
