name: DeviceMinder - UsersService CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.11"]
        redis-version: ["5.0.1"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: setup postgres
      uses: ikalnytskyi/action-setup-postgres@v5
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    - name: Install Dependecies
      run: |
        poetry install
    - name: Run Tests
      run: |
        sudo systemctl start postgresql.service
        cd src
        poetry run python tests.py
      env:
        ALGORITHM: ${{ secrets.ALGORITHM }}
        SERVICE_HOST: ${{ secrets.SERVICE_HOST }}
        SERVICE_PORT: ${{ secrets.SERVICE_PORT }}
        SQLALCHEMY_DATABASE_URL: ${{ secrets.SQLALCHEMY_DATABASE_URL }}
        POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
        POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
        POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        AUTH0_ALGORITHMS: ${{ secrets.AUTH0_ALGORITHMS }}
        AUTH0_ISSUER: ${{ secrets.AUTH0_ISSUER }}
        AUTH0_API_AUDIENCE: ${{ secrets.AUTH0_API_AUDIENCE }}
        APP_SECRET_KEY: ${{ secrets.APP_SECRET_KEY }}
        AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
        AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
